### ISSUE TITLE
which java version do you use?

### ISSUE THREAD

**Issue by aixuedegege** [JULIELab/java-stdio-ipc#1]
In my enviroment, when it run ""NumericIOPerformanceTest it give me an error:"predicate.not can not find symbol". How do i solve it. Could you give me some advice? Thank you very much.

**Comment by khituras** [comment]
`Predicate.not()` is a function introduced in Java 11. I just run the test with Java 11.0.2 which works fine.

**Comment by aixuedegege** [comment]
ok， thank you！It help me a lot.
